name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # (Nếu nhánh gốc của bạn tên là master thì sửa chữ main thành master)

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Quan trọng: Lệnh này giúp tải về toàn bộ lịch sử ngày giờ của Git

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cài đặt thư viện
        run: npm install

      - name: Đóng gói trang web (Tự động cập nhật ngày giờ)
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Tải file lên máy chủ Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Triển khai (Deploy)
        id: deployment
        uses: actions/deploy-pages@v4